mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#    global-config:
#      db-config:
#        id-type: auto
  global-config:
    db-config:
      #      logic-delete-field: showStatus # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
logging:
  level:
    com.atguigu.gulimall: debug
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss